Extension: made some tools aware of option --main (formely --single)

diff --git a/tools/confuzzius/scripts/do_solidity b/tools/confuzzius/scripts/do_solidity
--- a/tools/confuzzius/scripts/do_solidity
+++ b/tools/confuzzius/scripts/do_solidity
@@ -3,7 +3,7 @@
 FILENAME="$1"
 TIMEOUT="$2"
 BIN="$3"
-SINGLE="$4"
+MAIN="$4"
 
 export PATH="$BIN:$PATH"
 chmod +x "$BIN/solc"
@@ -15,9 +15,14 @@ COUNT=$(echo $CONTRACTS | wc -w)
 [ "$COUNT" -gt 0 ] || COUNT=1
 
 OPT_CONTRACT=""
-if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
-    COUNT=1
-    OPT_CONTRACT="--contract $CONTRACT"
+if [ "$MAIN" -eq 1 ]; then
+    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
+        COUNT=1
+        OPT_CONTRACT="--contract $CONTRACT"
+    else
+        echo "Contract '$CONTRACT' not found in $FILENAME"
+        exit 16
+    fi
 fi
 
 # Fuzz each contract at least 10 seconds
diff --git a/tools/maian/scripts/do_solidity b/tools/maian/scripts/do_solidity
--- a/tools/maian/scripts/do_solidity
+++ b/tools/maian/scripts/do_solidity
@@ -2,7 +2,7 @@
 
 FILENAME="$1"
 BIN="$2"
-SINGLE="$3"
+MAIN="$3"
 
 export PATH="$BIN:$PATH"
 chmod +x $BIN/solc
@@ -10,8 +10,14 @@ chmod +x $BIN/solc
 CONTRACT="${FILENAME%.sol}"
 CONTRACT="${CONTRACT##*/}"
 CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")
-if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
-    CONTRACTS="$CONTRACT"
+
+if [ "$MAIN" -eq 1 ]; then
+    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
+        CONTRACTS="$CONTRACT"
+    else
+        echo "Contract '$CONTRACT' not found in $FILENAME"
+        exit 16
+    fi
 fi
 
 cd /MAIAN/tool; 
diff --git a/tools/mythril-0.23.15/scripts/do_solidity b/tools/mythril-0.23.15/scripts/do_solidity
--- a/tools/mythril-0.23.15/scripts/do_solidity
+++ b/tools/mythril-0.23.15/scripts/do_solidity
@@ -3,7 +3,7 @@
 FILENAME="$1"
 TIMEOUT="$2"
 BIN="$3"
-SINGLE="$4"
+MAIN="$4"
 
 export PATH="$BIN:$PATH"
 chmod +x "$BIN/solc"
@@ -13,9 +13,13 @@ CONTRACT="${CONTRACT##*/}"
 CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")
 
 OPT_CONTRACT=""
-if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
-    COUNT=1
-    OPT_CONTRACT=":$CONTRACT"
+if [ "$MAIN" -eq 1 ]; then
+    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
+        OPT_CONTRACT=":$CONTRACT"
+    else
+        echo "Contract '$CONTRACT' not found in $FILENAME"
+        exit 16
+    fi
 fi
 
 OPT_TIMEOUT=""
diff --git a/tools/oyente/scripts/do_solidity b/tools/oyente/scripts/do_solidity
--- a/tools/oyente/scripts/do_solidity
+++ b/tools/oyente/scripts/do_solidity
@@ -3,7 +3,7 @@
 FILENAME="$1"
 TIMEOUT="$2"
 BIN="$3"
-SINGLE="$4"
+MAIN="$4"
 
 export PATH="$BIN:$PATH"
 chmod +x "$BIN/solc"
@@ -11,10 +11,15 @@ chmod +x "$BIN/solc"
 CONTRACT="${FILENAME%.sol}"
 CONTRACT="${CONTRACT##*/}"
 CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")
+
 OPT_CONTRACT=""
-if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
-    COUNT=1
-    OPT_CONTRACT="--target-contracts $CONTRACT"
+if [ "$MAIN" -eq 1 ]; then
+    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
+        OPT_CONTRACT="--target-contracts $CONTRACT"
+    else
+        echo "Contract '$CONTRACT' not found in $FILENAME"
+        exit 16
+    fi
 fi
 
 cd /oyente
diff --git a/tools/sfuzz/scripts/do_solidity b/tools/sfuzz/scripts/do_solidity
--- a/tools/sfuzz/scripts/do_solidity
+++ b/tools/sfuzz/scripts/do_solidity
@@ -3,7 +3,7 @@
 FILENAME="$1"
 TIMEOUT="$2"
 BIN="$3"
-SINGLE="$4"
+MAIN="$4"
 
 export PATH="$BIN:$PATH"
 chmod +x "$BIN/solc"
@@ -13,9 +13,15 @@ CONTRACT="${CONTRACT##*/}"
 CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")
 COUNT=$(echo $CONTRACTS | wc -w)
 [ "$COUNT" -gt 0 ] || COUNT=1
-if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
-    COUNT=1
-    CONTRACTS="$CONTRACT"
+
+if [ "$MAIN" -eq 1 ]; then
+    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
+        CONTRACTS="$CONTRACT"
+        COUNT=1
+    else
+        echo "Contract '$CONTRACT' not found in $FILENAME"
+        exit 16
+    fi
 fi
 
 mkdir -p /home/contracts
